# .github/workflows/main.yml
# Copy/pasted from https://angular.io/guide/testing#configure-project-for-github-actions
name: CI Nest.js app through Github Actions
on: push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Setup
        run: npm ci

      - name: Test
        run: npm test
